"use client"

import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Plus, Sparkles } from "lucide-react"
import type { LlmSuggestion } from "@/types/web-source"

interface LlmSuggestionsProps {
  suggestions: LlmSuggestion[]
  onAddSuggestion: (suggestion: LlmSuggestion) => void
}

export function LlmSuggestions({ suggestions, onAddSuggestion }: LlmSuggestionsProps) {
  if (suggestions.length === 0) {
    return <Card className="p-4 text-center text-gray-500">No AI suggestions available for this page.</Card>
  }

  return (
    <div className="space-y-3">
      {suggestions.map((suggestion) => (
        <Card key={suggestion.id} className="p-4 hover:shadow-md transition-shadow">
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <h3 className="font-medium">{suggestion.name}</h3>
                <Badge variant="outline" className="text-xs">
                  {suggestion.dataType}
                </Badge>
              </div>
              <p className="text-sm text-gray-600 mb-2">{suggestion.description}</p>
              <div className="text-xs text-gray-500">
                <span className="font-medium">{suggestion.extractionMethod}:</span>{" "}
                <code className="bg-gray-100 px-1 py-0.5 rounded">{suggestion.extractionRule}</code>
              </div>
            </div>
            <Button
              size="sm"
              variant="ghost"
              className="text-green-600 hover:text-green-700 hover:bg-green-50"
              onClick={() => onAddSuggestion(suggestion)}
            >
              <Plus className="h-4 w-4 mr-1" />
              Add
            </Button>
          </div>
        </Card>
      ))}

      <div className="flex items-center justify-center mt-2 text-xs text-gray-500">
        <Sparkles className="h-3 w-3 mr-1 text-amber-500" />
        Suggestions generated by AI based on page analysis
      </div>
    </div>
  )
}
